Fix Python install in Travis on macOS

diff --git a/.ci/brew/install b/.ci/brew/install
--- a/.ci/brew/install
+++ b/.ci/brew/install
@@ -4,6 +4,11 @@ set -ev
 
 export PYTHON=${PYTHON:-python}
 
+# WARNING The Python environment in Travis is weird: "brew install python" fails
+# when symlinking, due to the presence of python@2.
+brew upgrade python || brew install python || true
+brew link --overwrite python || true
+
 for PACKAGE in boost cmake libomp pybind11; do
     VERSIONS=$(brew ls --versions ${PACKAGE} || true)
     if [ -z "${VERSIONS}" ]; then
@@ -21,8 +26,6 @@ for PACKAGE in boost cmake libomp pybind11; do
         brew ${COMMAND} ${PACKAGE}
     fi
 done
-# Cannot link correctly due to python@2: overwrite conflicting links
-brew link --overwrite python
 
 NUMPY=$(${PYTHON} -c 'import sys; print("numpy" if sys.version >= "3.5" else "numpy<=1.16.4")')
 ${PYTHON} -m pip install -U ${NUMPY}
